### ISSUE TITLE
UI Slider Feedback SFX

### ISSUE THREAD

**Issue by Irkedibis** [GDACollab/TacoCat#239]
UI & Menu SFX Folder: https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=sharing
SFX Checklist: https://docs.google.com/spreadsheets/d/1p6o-WQsl1Hy2EW_-neKIY4pfV3HE_lr5xGYMFvKN7fs/edit?usp=sharing

Please create a **short, simple, yet thematic sound that can be repeated multiple times back-to-back.** This is for when the player messes with the volume sliders (discrete volume values, not continuous) while in the audio settings. When they're interacting with the slider, a sound will be play at each discrete value

Some options for the sound include:

- Short bell
- Meow
- A text jingle
- and more!

Please upload your asset(s) into the UI & Menu SFX folder, leave a comment below linking to the folder, along with the name of the asset(s) you uploaded

**Comment by JeremyH0451** [comment]
Simple tap sound for the volume slider feedback sfx.
[https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link](https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link)

**Comment by JeremyH0451** [comment]
2 New tap sounds for the volume slider. 1st one is the original beep but with less bass, the 2nd one is a click instead of a beep because I didn't really like the tonality of the beep. They are called "sfx_UI_VolumeSlider_JeremyHahn_(bass subtracted).wav" and "sfx_UI_VolumeSlider_JeremyHahn_V2.wav" respectively. 
[https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link](https://drive.google.com/drive/folders/12zJ1X645Qnav9dGr3FXGGvnoym03VZN4?usp=share_link)
